-- 004_voyage_1024_dims.sql
-- Migrate the embedding backend from the local bge-small-en-v1.5 model (384
-- dims) to Voyage AI `voyage-3.5-lite` (1024 dims). The embedding column type
-- changes from vector(384) to vector(1024). Written idempotently so a manual
-- re-run is safe; the runner wraps this in a transaction.
--
-- RE-INDEX REQUIRED: stored 384-dim vectors are produced by a different model
-- and are meaningless at 1024 dims, so they CANNOT be converted — they are
-- cleared to NULL here and every chunk must be re-embedded by running:
--
--     pnpm --filter @max/sandbox ingest
--
-- The ingest skip-by-content_hash idempotency has been updated to NOT skip
-- documents that have chunks with NULL embeddings, so a normal ingest run
-- after this migration WILL re-embed all chunks.

-- The HNSW index is bound to the old dimensionality; drop it before altering
-- the column type.
DROP INDEX IF EXISTS chunks_embedding_hnsw_cosine_idx;

-- Clear the old 384-dim vectors and widen the column to 1024 dims in one step.
-- USING NULL discards the incompatible vectors (they must be regenerated by
-- Voyage); the column is already nullable, so this leaves chunks intact and
-- flagged as "needs embedding".
ALTER TABLE chunks
  ALTER COLUMN embedding TYPE vector(1024) USING NULL;

-- Recreate the HNSW cosine index on the new vector(1024) column, matching the
-- name and opclass from 001 so it stays idempotent across re-runs.
CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_cosine_idx
  ON chunks USING hnsw (embedding vector_cosine_ops);
